services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prospecta_crm
    ports:
      - "5432:5432"
    volumes:
      - prospecta_db_data:/var/lib/postgresql/data

volumes:
  prospecta_db_data:
